name = "TetGen"
uuid = "c5d3f3f7-f850-59f6-8a2e-ffc6dc1317ea"
authors = ["SimonDanisch <sdanisch@gmail.com>", "Juergen Fuhrmann <juergen.fuhrmann@wias-berlin.de"]
version = "1.2.1"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TetGen_jll = "b47fdcd6-d2c1-58e9-bbba-c1cee8d8c179"

[compat]
DocStringExtensions = "^0.8"
GeometryBasics = "0.2, 0.3, 0.4"
StaticArrays = "1"
TetGen_jll = "1.5.1"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
